Models/HOJA_COSTO_PNP.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace AppWebHojaCosto.Models
{
    public class HOJA_COSTO_PNP
    {
        public string TipoHojaCosto { get; set; }
        public TBL_HOJA_COSTO_PNP TBL_HOJA_COSTO_PNP { get; set; }
        public IEnumerable<TBL_HOJA_COSTO_PNP> LST_TBL_HOJA_COSTO_PNP { get; set; }
        public IEnumerable<TBL_SIM_HOJA_COSTO_PNP> LST_TBL_SIM_HOJA_COSTO_PNP { get; set; }
        public IEnumerable<SelectListItem> TipoHojas { get; set; }
        public IEnumerable<SelectListItem> Referencias { get; set; }
        public IEnumerable<SelectListItem> Marcas { get; set; }
        public IEnumerable<SelectListItem> Colecciones { get; set; }
        public IEnumerable<SelectListItem> Lineas { get; set; }
        public IEnumerable<SelectListItem> Estados { get; set; }
    }
}

Controllers/HojaCostoPNPController.cs
using AppWebHojaCosto.Models;
using AppWebHojaCosto.Services;
using FastMember;
using Microsoft.Reporting.WebForms;
//using SelectPdf;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;
using System.Drawing.Printing;
using Spire.Pdf.Annotations;
using Spire.Pdf.Widget;
using Spire.Pdf;
using Ionic.Zip;
using System.IO;
using System;
using System.Diagnostics;
using iTextSharp.text;
using iTextSharp.text.pdf;
using AppWebHojaCosto.Controllers.Helpers;

namespace AppWebHojaCosto.Controllers
{
    public class HojaCostoPNPController : Controller
    {
        private HojaCostoPNPService _services;

        public HojaCostoPNPController()
        {
            _services = new HojaCostoPNPService();
        }

        public HOJA_COSTO_PNP LoadModel()
        {
            var model = new HOJA_COSTO_PNP();
            return model;
        }

        public HOJA_COSTO_PNP CargarTabla(HOJA_COSTO_PNP model)
        {
            HOJA_COSTO_PNP _model = _services._LST_COSTO_PNP(model.TipoHojaCosto, model.TBL_HOJA_COSTO_PNP.PnpMarcaS, model.TBL_HOJA_COSTO_PNP.PnpColeccionS, model.TBL_HOJA_COSTO_PNP.PnpLineaS, model.TBL_HOJA_COSTO_PNP.PnpEstadoS);
            _model.TipoHojaCosto = model.TipoHojaCosto;
            _model.Referencias = GetSelectListItems(new List<string>());
            _model.TipoHojas = _services.ObtenerTiposHojas();
            _model.Marcas = GetSelectListItems(new List<string> { model.TBL_HOJA_COSTO_PNP.PnpMarcaS });
            _model.Colecciones = GetSelectListItems(new List<string> { model.TBL_HOJA_COSTO_PNP.PnpColeccionS });
            _model.Lineas = GetSelectListItems(new List<string> { model.TBL_HOJA_COSTO_PNP.PnpLineaS });
            _model.Estados = GetSelectListItems(new List<string> { model.TBL_HOJA_COSTO_PNP.PnpEstadoS });
            _model.TBL_HOJA_COSTO_PNP = model.TBL_HOJA_COSTO_PNP;
            return _model;
        }

        // GET: HojaCostoPNP
        public ActionResult Index()
        {
            var model = LoadModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult ConsultarxRef(HOJA_COSTO_PNP model)
        {
            try
            {
                if (model.TBL_HOJA_COSTO_PNP.PnpReferenciaS != null && model.TipoHojaCosto != null)
                {
                    if (model.TipoHojaCosto == "CE")
                    {
                        TBL_HOJA_COSTO_PNP _model = _services._HOJA_COSTO_PNP(model.TBL_HOJA_COSTO_PNP.PnpReferenciaS);
                        if (_model != null)
                        {
                            return RedirectToAction("Index", "HojaNoProducido", new { Referencia = model.TBL_HOJA_COSTO_PNP.PnpReferenciaS });
                        }
                        else
                        {
                            ViewBag.cargar_listas = "X";
                            ViewBag.alerta = "La referencia no existe.";
                            return View("Index", model);
                        }
                    }
                    else if (model.TipoHojaCosto == "CS")
                    {
                        return RedirectToAction("Index", "HojaNoProducidoSimulada", new { Referencia = model.TBL_HOJA_COSTO_PNP.PnpReferenciaS });
                    }
                    return View("Index", model);
                }
                else
                {
                    ViewBag.alerta = "Falta datos por diligenciar.";
                    return View("Index", model);
                }
            }
            catch (Exception ex)
            {
                ViewBag.error = "Se presentó un error, detalle: " + ex.Message;
                return View("Index", model);
            }
        }

        public ActionResult ConsultarxRef(string Tipo, string Referencia)
        {
            try
            {
                if (Referencia != null && Tipo != null)
                {
                    if (Tipo == "CE")
                    {
                        return RedirectToAction("Index", "HojaNoProducido", new { Referencia = Referencia });
                    }
                    else if (Tipo == "CS")
                    {
                        return RedirectToAction("Index", "HojaNoProducidoSimulada", new { Referencia = Referencia });
                    }
                    ViewBag.alerta = "Se presentaron problemas al cargar";
                    return RedirectToAction("Index");
                }
                return View("Index", null);
            }
            catch(Exception ex)
            {
                ViewBag.error = "Se presentó un error, detalle: " + ex.Message;
                return View("Index", null);
            }
        }

        [HttpPost]
        public ActionResult ConsultaMasiva(HOJA_COSTO_PNP model)
        {
            if (model.TBL_HOJA_COSTO_PNP.PnpMarcaS != null && model.TBL_HOJA_COSTO_PNP.PnpColeccionS != null && model.TipoHojaCosto != null)
            {
                var _model = CargarTabla(model);
                ViewBag.cargar_listas = "X";
                return View("Index", _model);
            }
            else
            {
                model.Referencias = GetSelectListItems(new List<string>());
                model.TipoHojas = _services.ObtenerTiposHojas();
                model.Marcas = GetSelectListItems(new List<string>());
                model.Colecciones = GetSelectListItems(new List<string>());
                model.Lineas = GetSelectListItems(new List<string>());
                model.Estados = GetSelectListItems(new List<string>());
                ViewBag.alerta = "Falta datos por diligenciar.";
                return View("Index", model);
            }
        }

        [HttpPost]
        public ActionResult GenerarPdf(HOJA_COSTO_PNP model, string Referencias)
        {
            Guid miGuid = Guid.NewGuid();
            string nombre = miGuid.ToString();
            try
            {
                Referencias = Referencias.TrimEnd('|');
                string[] split = Referencias.Split('|');
                List<string> archivos = new List<string>();
                foreach (string var in split)
                {
                    //Ejecuto el reporte para obtener el informe en bytes
                    LocalReport localReport = new LocalReport();
                    if (model.TipoHojaCosto == "CE")
                        localReport.ReportPath = Server.MapPath("~/Reports/ReportHojaCostoPNP.rdlc");
                    else if (model.TipoHojaCosto == "CS")
                        localReport.ReportPath = Server.MapPath("~/Reports/ReportHojaCostoSimPNP.rdlc");

                    ReportDataSource reportDataSource = new ReportDataSource();
                    reportDataSource.Name = "dsHojaCostoPNP";

                    if (model.TipoHojaCosto == "CE")
                    {
                        var data = _services._LST_HOJA_COSTO_PNP(var);
                        reportDataSource.Value = data;
                    }
                    else if (model.TipoHojaCosto == "CS")
                    {
                        var data = _services._LST__HOJA_SIM_COSTO_PNP(var);
                        reportDataSource.Value = data;
                    }

                    localReport.EnableExternalImages = true;
                    localReport.DataSources.Add(reportDataSource);
                    string reportType = "PDF";
                    string mimeType = "PDF";
                    string encoding;
                    string fileNameExtension;
                    string deviceInfo = "";
                    Warning[] warnings;
                    string[] streams;
                    byte[] renderedBytes;

                    //Renderizo el reporte en bytes para luego enviarse a imprimir
                    renderedBytes = localReport.Render(reportType, deviceInfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);

                    //Guardo el archivo en formato pdf para su impresion posterior
                    var dataFile = Server.MapPath("~/Documents/" + var + ".pdf");
                    System.IO.File.WriteAllBytes(dataFile, renderedBytes);

                    archivos.Add(Server.MapPath("~/Documents/" + var + ".pdf"));

                    //ImprimirPdf(dataFile);
                    //SendToPrinter(dataFile);
                }
                CombinePDF.CombineMultiplePDFs(archivos, Server.MapPath("~/Documents/" + nombre + ".pdf"));
            }
            catch (Exception ex)
            {
                ViewBag.error = "Ocurrio un error al procesar la solicitud";
                return View("Index", LoadModel());
            }

            //ViewBag.exito = "Proceso terminado correctamente";
            ViewBag.pdf = nombre + ".pdf";
            return View("Index", CargarTabla(model));
        }

        private void SendToPrinter(string pdf)
        {
            ProcessStartInfo info = new ProcessStartInfo();
            info.Verb = "print";
            info.FileName = pdf;
            info.CreateNoWindow = true;
            info.WindowStyle = ProcessWindowStyle.Hidden;

            Process p = new Process();
            p.StartInfo = info;
            p.Start();

            p.WaitForInputIdle();
            System.Threading.Thread.Sleep(3000);
            if (false == p.CloseMainWindow())
                p.Kill();
        }

        [HttpPost]
        public virtual ActionResult ExportExcel(HOJA_COSTO_PNP model, string Referencias)
        {
            try
            {
                ZipFile zip = new ZipFile();
                var nombreZip = "Hojas_costo.zip";
                Referencias = Referencias.TrimEnd('|');
                string[] split = Referencias.Split('|');
                foreach (string var in split)
                {
                    //Ejecuto el reporte para obtener el informe en bytes
                    LocalReport localReport = new LocalReport();

Views/HojaCostoPNP/Index.cshtml
@model AppWebHojaCosto.Models.HOJA_COSTO_PNP

@{
    ViewBag.Title = "Producto No Producido";
}

@section Scripts {
    <style>
        .custom-combobox {
            width: 100%;
            position: relative;
            display: inline-block;
        }

        .custom-combobox-toggle {
            position: absolute;
            top: 0;
            bottom: 0;
            right: 0;
            margin-right: -1px;
            padding: 0;
        }

        .custom-combobox-input {
            margin: 0;
            padding: 5px 10px;
        }
    </style>
    <script src="~/Scripts/JS/js-hoja-costo-no-producido.js"></script>

    @if (ViewBag.alerta != null)
    {
        <script type="text/javascript">
                alerta("Alerta!", '@ViewBag.alerta');
        </script>
    }
    @if (ViewBag.error != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alerta("Error!", '@ViewBag.error');
        };
        </script>
    }
    @if (ViewBag.exito != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alerta("Exito!", '@ViewBag.exito');
        };
        </script>
    }
    @if (ViewBag.pdf != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                //printJS('../../consolidado.pdf');
                printJS('../../Documents/@ViewBag.pdf');
            };
        </script>
    }
    @if (ViewBag.cargar_listas != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                FiltroRef();
                FiltroMarca2();
                FiltroColeccion();
                FiltroLinea("");
                FiltroEstado("");
            };
        </script>
    }
}

<h4 style="text-align:center;">PRODUCTO NO PRODUCIDO</h4>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            @{Html.RenderPartial("_InfoxReferencia", Model);}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @{Html.RenderPartial("_InfoMasiva", Model);}
        </div>
    </div>
</div>

Views/HojaCostoPNP/_InfoMasiva.cshtml
@model AppWebHojaCosto.Models.HOJA_COSTO_PNP

<fieldset style="border-width:2px; border-style:groove; padding:10px;">
    <legend style="padding: 2px; width:auto;">Generación Impresion Masiva</legend>
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "FrmMasiva" }))
    {
        <div class="row">
            <div class="col-md-2">
                <label>Tipo <span class="text-danger">(*)</span></label>
                @*@Html.DropDownListFor(m => m.TipoHojaCosto, Model.TipoHojas, new { @id = "Tipo", @class = "form-control", @onclick = "FiltroMarca();" })*@
                @Html.DropDownListFor(model => model.TipoHojaCosto, new SelectList(
                  new List<Object>{
                       new { value = "" , text = "--Seleccione--"  },
                       new { value = "CE" , text = "Hoja de Costo Estandar"  },
                       new { value = "CS" , text = "Hoja de Costo Simulada" }
                    },
                  "value",
                  "text",
                   0), new { @id = "Tipo", @class = "form-control", @onclick = "FiltroMarca();" })
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.LST_TBL_HOJA_COSTO_PNP.FirstOrDefault().PnpMarcaS, new { @class = "control-label" })<span class="text-danger">(*)</span>
                @*@Html.DropDownListFor(m => m.TBL_HOJA_COSTO_PNP.PnpMarcaS, new SelectList(Model.Marcas, "Value", "Text"), new { @id = "Marca", @class = "form-control" })*@
                <div class="input-group">
                    @Html.TextBoxFor(m => m.TBL_HOJA_COSTO_PNP.PnpMarcaS, new { @id = "Marca", @type = "search", @required = "required", @class = "form-control py-2 border-right-0 border" })
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button" id="ver-todo-marcas">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.LST_TBL_HOJA_COSTO_PNP.FirstOrDefault().PnpColeccionS, new { @class = "control-label" })<span class="text-danger">(*)</span>
                @*@Html.DropDownListFor(m => m.TBL_HOJA_COSTO_PNP.PnpColeccionS, new SelectList(Model.Colecciones, "Value", "Text"), new { @id = "Coleccion", @class = "form-control" })*@
                <div class="input-group">
                    @Html.TextBoxFor(m => m.TBL_HOJA_COSTO_PNP.PnpColeccionS, new { @id = "Coleccion", @type = "search", @required = "required", @class = "form-control py-2 border-right-0 border" })
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button" id="ver-todo-coleccion">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.LST_TBL_HOJA_COSTO_PNP.FirstOrDefault().PnpLineaS, new { @class = "control-label" })
                @*@Html.DropDownListFor(m => m.TBL_HOJA_COSTO_PNP.PnpLineaS, new SelectList(Model.Lineas, "Value", "Text"), new { @id = "Linea", @class = "form-control" })*@
                <div class="input-group">
                    @Html.TextBoxFor(m => m.TBL_HOJA_COSTO_PNP.PnpLineaS, new { @id = "Linea", @type = "search", @class = "form-control py-2 border-right-0 border" })
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button" id="ver-todo-linea">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.LST_TBL_HOJA_COSTO_PNP.FirstOrDefault().PnpEstadoS, new { @class = "control-label" })
                @*@Html.DropDownListFor(m => m.TBL_HOJA_COSTO_PNP.PnpEstadoS, new SelectList(Model.Estados, "Value", "Text"), new { @id = "Estado", @class = "form-control" })*@
                <div class="input-group">
                    @Html.TextBoxFor(m => m.TBL_HOJA_COSTO_PNP.PnpEstadoS, new { @id = "Estado", @type = "search", @class = "form-control py-2 border-right-0 border" })
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button" id="ver-todo-estado">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                <div style="height:33px; width:10px;"></div>
                <button type="submit" class="btn btn-sm btn-dark" formaction="ConsultaMasiva"><span class="fa fa-search"></span> Consultar</button>
                <button type="button" id="btnLimpiar" class="btn btn-sm btn-dark" onclick="return false;"><span class="fa fa-undo"></span> Limpiar</button>
            </div>
        </div>
        <div class="row" style="padding-top:20px;">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered" id="table" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Referencia</th>
                                <th>Descripción</th>
                                <th>Estado</th>
                                <th>Acción</th>
                                <th>Marca</th>
                                <th>Linea</th>
                                <th>Usuario Costos</th>
                                <th>Orden Compra</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                if (Model.LST_TBL_HOJA_COSTO_PNP != null)
                                {
                                    foreach (var item in Model.LST_TBL_HOJA_COSTO_PNP)
                                    {
                                        <tr>
                                            <td>@item.PnpReferenciaS</td>
                                            <td>@item.PnpDescripS</td>
                                            <td>@item.PnpEstadoS</td>
                                            <td>@Html.ActionLink("Visualizar", "ConsultarxRef", new { Tipo = Model.TipoHojaCosto, Referencia = item.PnpReferenciaS })</td>
                                            <td>@item.PnpMarcaS</td>
                                            <td>@item.PnpLineaS</td>
                                            <td>@item.PnpUsuCostoS</td>
                                            <td>@item.PnpOrdenCompraS</td>
                                        </tr>
                                    }
                                }
                                if (Model.LST_TBL_SIM_HOJA_COSTO_PNP != null)
                                {
                                    foreach (var item in Model.LST_TBL_SIM_HOJA_COSTO_PNP)
                                    {
                                        <tr>
                                            <td>@item.SimPnpReferenciaS</td>
                                            <td>@item.SimPnpDescripS</td>
                                            <td>@item.SimPnpEstadoS</td>
                                            <td>@Html.ActionLink("Visualizar", "ConsultarxRef", new { Tipo = Model.TipoHojaCosto, Referencia = item.SimPnpReferenciaS })</td>
                                            <td>@item.SimPnpMarcaS</td>
                                            <td>@item.SimPnpLineaS</td>
                                            <td>@item.SimPnpUsuCostoS</td>
                                            <td>@item.SimPnpOrdenCompraS</td>
                                        </tr>
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row" style="text-align:center; padding-top:20px;">
            <div class="col-md-12">
                @Html.Hidden("Referencias", null, new { Id = "Referencias", Value = "" })
                <button type="submit" id="Exportar" formaction="Export" class="btn btn-sm btn-dark" formnovalidate disabled><span class="fa fa-download"></span> Exportar</button>
                <button type="submit" id="Imprimir" formaction="GenerarPdf" class="btn btn-sm btn-dark" formnovalidate disabled><span class="fa fa-print"></span> Imprimir</button>
                <button type="submit" id="Cerrar" formaction="CerrarHojas" class="btn btn-sm btn-dark" formnovalidate disabled><span class="fa fa-check-circle"></span> Cerrar Hojas</button>
            </div>
        </div>
    }
</fieldset>

Views/HojaCostoPNP/_InfoxReferencia.cshtml
@model AppWebHojaCosto.Models.HOJA_COSTO_PNP

@using (Html.BeginForm("ConsultarxRef", "HojaCostoPNP", FormMethod.Post))
{
    <fieldset style="border-width:2px; border-style:groove; padding:10px;">
        <legend style="padding: 2px; width:auto;">Consulta Hoja de Costo por Referencias</legend>
        <div class="row" id="FrmRef">
            <div class="col-md-5">
                <label>Tipo de Hoja de Costo: <span class="text-danger">(*)</span></label>
                @*@Html.DropDownListFor(m => m.TipoHojaCosto, new SelectList(Model.TipoHojas, "Value", "Text"), new { @id = "TipoCab", @class = "form-control", @onclick = "FiltroRef();" })*@
                @Html.DropDownListFor(model => model.TipoHojaCosto, new SelectList(
                  new List<Object>{
                       new { value = "" , text = "--Seleccione--"  },
                       new { value = "CE" , text = "Hoja de Costo Estandar"  },
                       new { value = "CS" , text = "Hoja de Costo Simulada" }
                    },
                  "value",
                  "text",
                   0), new { @id = "TipoCab", @class = "form-control", @onclick = "FiltroRef();" })
            </div>
            <div class="col-md-5">
                <label>Consulta hoja de costo x referencia: <span class="text-danger">(*)</span></label>
                @*@Html.DropDownListFor(m => m.TBL_HOJA_COSTO_PNP.PnpReferenciaS, new SelectList(Model.Referencias, "Value", "Text"), new { @id = "Referencia", @class = "form-control" })*@
                <div class="input-group">
                    @Html.TextBoxFor(m => m.TBL_HOJA_COSTO_PNP.PnpReferenciaS, new { @id = "Referencia", @type = "search", @class = "form-control py-2 border-right-0 border" })
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button" id="ver-todo-ref">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                <div style="height:33px; width:10px;">
                </div>
                <button type="submit" class="btn btn-sm btn-dark"><span class="fa fa-search"></span> Consultar</button>
            </div>
        </div>
    </fieldset>
}