Controllers/ParametrosController.cs
using AppWebHojaCosto.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppWebHojaCosto.Services;
using System.IO;
using OfficeOpenXml;

namespace AppWebHojaCosto.Controllers
{
    public class ParametrosController : Controller
    {
        private ParametrosServices _services;

        public ParametrosController()
        {
            _services = new ParametrosServices();
        }

        // GET: Parametros
        public ActionResult Index()
        {
            PARAMETROS_PN model = new PARAMETROS_PN();
            model.Marcas = GetSelectListItems(new List<string>());
            model.Colecciones = GetSelectListItems(new List<string>());
            model.Lineas = GetSelectListItems(new List<string>());
            model.Sublineas = GetSelectListItems(new List<string>());
            return View(model);
        }

        [HttpPost]
        public ActionResult FiltroMarca(string Tipo)
        {
            var marcas = _services.obtenerMarcas(Tipo);
            return Json(marcas, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult FiltroColeccion(string Tipo, string Marca)
        {
            var colecciones = _services.obtenerColecciones(Tipo, Marca);
            return Json(colecciones, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult FiltroLinea(string Tipo, string Marca, string Coleccion)
        {
            var lineas = _services.obtenerLineas(Tipo, Marca, Coleccion);
            return Json(lineas, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult FiltroSublinea(string Tipo, string Marca, string Coleccion, string Linea)
        {
            var sublineas = _services.obtenerSublineas(Tipo, Marca, Coleccion, Linea);
            return Json(sublineas, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Consultar(string Factor, string marca, string coleccion, string linea, string sublinea/*PARAMETROS_PN model*/)
        {
            try
            {
                ViewBag.marca = marca;
                ViewBag.coleccion = coleccion;
                ViewBag.linea = linea;
                ViewBag.sublinea = sublinea;

                if (Factor == "" || Factor == null)
                {
                    ViewBag.alerta = "Debe seleccionar un tipo.";
                    //return View("Index", model);
                }

                //PARAMETROS_PN _model = _services.obtenerParametros(model.Factor, model._TBL_PARAM_PN.PpMarcaS, model._TBL_PARAM_PN.PpColeccionS, model._TBL_PARAM_PN.PpLineaS, model._TBL_PARAM_PN.PpSubLineaS);
                PARAMETROS_PN _model = _services.obtenerParametros(Factor, marca, coleccion, linea, sublinea);
                if (_model._TBL_PARAM_PN != null)
                {
                    ViewBag.habilitar = "S";
                }
                else
                {
                    ViewBag.alerta = "No existen registros para mostrar";
                }

                return View("Index", _model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPost]
        public ActionResult Actualizar(PARAMETROS_PN model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    String mensaje = _services.actualizar_crearParametros(model._TBL_PARAM_PN);
                    string viewContent = ConvertViewToString("_Formulario", model);
                    return Json(new { PartialView = viewContent, mensaje = mensaje });
                    //return PartialView("_Formulario", parametros);
                }
                else
                {
                    //var errors = ModelState.Select(x => x.Value.Errors)
                    //           .Where(y => y.Count > 0)
                    //           .ToList();
                    string viewContent = ConvertViewToString("_Formulario", model);
                    return Json(new { PartialView = viewContent, mensaje_warning = "Valide la información ingresada" });
                    //return PartialView("_Formulario", parametros);
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPost]
        public ActionResult Crear(PARAMETROS_PN model, string marca, string coleccion, string linea, string sublinea)
        {
            try
            {
                string viewContent;
                if (model._TBL_PARAM_PN.PpCodigoN == 0)
                {
                    if (model.Factor != null && marca.Length > 0 && coleccion.Length > 0 && linea.Length > 0 && sublinea.Length > 0)
                    {
                        model._TBL_PARAM_PN.PpFactorS = model.Factor;
                        model._TBL_PARAM_PN.PpMarcaS = marca;
                        model._TBL_PARAM_PN.PpColeccionS = coleccion;
                        model._TBL_PARAM_PN.PpLineaS = linea;
                        model._TBL_PARAM_PN.PpSubLineaS = sublinea;
                        model._TBL_PARAM_PN.PpCodigoN = 0;
                        model._TBL_PARAM_PN.PpFecCreD = DateTime.Now;
                        string mensaje = _services.actualizar_crearParametros(model._TBL_PARAM_PN);
                        viewContent = ConvertViewToString("_Formulario", model);
                        return Json(new { PartialView = viewContent, mensaje = mensaje });
                    }
                    else
                    {
                        viewContent = ConvertViewToString("_Formulario", model);
                        return Json(new { PartialView = viewContent, mensaje_warning = "Valide la información ingresada" });
                    }
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        if (model._TBL_PARAM_PN.PpMarcaS.Equals(marca) && model._TBL_PARAM_PN.PpColeccionS.Equals(coleccion) && model._TBL_PARAM_PN.PpLineaS.Equals(linea)
                            && model._TBL_PARAM_PN.PpSubLineaS.Equals(sublinea))
                        {
                            viewContent = ConvertViewToString("_Formulario", model);
                            return Json(new { PartialView = viewContent, mensaje_warning = "El registro ya existe." });
                        }
                        else
                        {
                            model._TBL_PARAM_PN.PpMarcaS = marca;
                            model._TBL_PARAM_PN.PpColeccionS = coleccion;
                            model._TBL_PARAM_PN.PpLineaS = linea;
                            model._TBL_PARAM_PN.PpSubLineaS = sublinea;
                            model._TBL_PARAM_PN.PpCodigoN = 0;
                            model._TBL_PARAM_PN.PpFecCreD = DateTime.Now;
                            String mensaje = _services.actualizar_crearParametros(model._TBL_PARAM_PN);
                            viewContent = ConvertViewToString("_Formulario", model);
                            return Json(new { PartialView = viewContent, mensaje = mensaje });
                            //return PartialView("_Formulario", parametros);
                        }
                    }
                    else
                    {
                        //var errors = ModelState.Select(x => x.Value.Errors)
                        //           .Where(y => y.Count > 0)
                        //           .ToList();
                        viewContent = ConvertViewToString("_Formulario", model);
                        return Json(new { PartialView = viewContent, mensaje_warning = "Valide la información ingresada" });
                        //return PartialView("_Formulario", parametros);
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        private string ConvertViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (StringWriter writer = new StringWriter())
            {
                ViewEngineResult vResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext vContext = new ViewContext(this.ControllerContext, vResult.View, ViewData, new TempDataDictionary(), writer);
                vResult.View.Render(vContext, writer);
                return writer.ToString();
            }
        }

        private IEnumerable<SelectListItem> GetSelectListItems(IEnumerable<string> elements)
        {
            var selectList = new List<SelectListItem>();

            foreach (var element in elements)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element,
                    Text = element
                });
            }
            return selectList;
        }

        //FALTA AÑADIR LOS VALORES NUEVOS
        public ActionResult Upload(FormCollection formCollection)
        {
            try
            {
                if (Request != null)
                {
                    HttpPostedFileBase file = Request.Files["UploadedFile"];

                    if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName))
                    {
                        string fileName = file.FileName;
                        string fileContentType = file.ContentType;
                        byte[] fileBytes = new byte[file.ContentLength];
                        var data = file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));
                        List<string> lstStatus = new List<string>();
                        using (var package = new ExcelPackage(file.InputStream))

Views/Parametros/Index.cshtml
@model AppWebHojaCosto.Models.PARAMETROS_PN

@{
    ViewBag.Title = "Index";
}

@section Scripts {
    <script src="~/Scripts/JS/js-parametros-producido.js"></script>
    <script>
    </script>

    @if (ViewBag.marca != null && ViewBag.coleccion != null && ViewBag.linea != null && ViewBag.sublinea != null)
    {
        <script type="text/javascript">
            $("#marca").val('@ViewBag.marca');
            $("#coleccion").val('@ViewBag.coleccion');
            $("#linea").val('@ViewBag.linea');
            $("#sublinea").val('@ViewBag.sublinea');
            FiltroMarca();
            FiltroColeccion();
            FiltroLinea();
            FiltroSublinea("");
        </script>
    }
    @if (ViewBag.alerta != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alerta("Alerta!", '@ViewBag.alerta');
        };
        </script>
    }
    @if (ViewBag.error != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alerta("Error!", '@ViewBag.error');
        };
        </script>
    }
    @if (ViewBag.exito != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alerta("Exito!", '@ViewBag.exito');
        };
        </script>
    }
    @if (ViewBag.habilitar != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                $('#btnCargar').prop("disabled", false);
                $('#btnActualizar').prop("disabled", false);
                $('#Contenedor input').prop("disabled", false);
            };
        </script>
    }

    @if (ViewBag.warning != null)
    {
        <script type="text/javascript">
        window.onload = function () {
            alerta("Alerta!", '@ViewBag.warning');
        };
        </script>
    }
    @if (ViewBag.estado != null && ViewBag.estado == "W")
    {
        <script type="text/javascript">
        window.onload = function () {
            alerta("Mensaje", "@ViewBag.mensaje");
            $('#modalLogs').modal('show');
        };
        </script>
    }
    @if (ViewBag.estado != null && ViewBag.estado == "E")
    {
        <script type="text/javascript">
            window.onload = function () {
            alerta("Exito!", '@ViewBag.mensaje');
        };
        </script>
    }
}

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="@Url.Action("Index","Home")">Inicio</a>
    </li>
</ol>

<div id="formConsultar">
    @{Html.RenderPartial("_Consultar", Model);}
</div>

<br />

<div id="myform">
    @{Html.RenderPartial("_Formulario", Model);}
</div>

<!-- Modal cargar archivo -->
<div class="modal fade" id="modalCargar" tabindex="-1" role="dialog" aria-labelledby="modalCargar" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalBorrar">Cargar documento</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Upload", "Parametros", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <input type="file" name="UploadedFile" class="form-control" />
                            </div>
                        </div>
                        <br />
                        <div class="row" style="text-align:center;">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-sm btn-dark"><span class="fa fa-save"></span> Guardar</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button class="btn btn-sm btn-dark" type="button" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal cargar archivo -->
<div class="modal fade" id="modalLogs" tabindex="-1" role="dialog" aria-labelledby="modalLogs" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLogs">Estado cargue</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <br />
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Mensaje</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (ViewBag.lstStatus != null)
                        {
                            foreach (var data in ViewBag.lstStatus)
                            {
                                <tr>
                                    <td>@data</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <br />
            </div>
        </div>
    </div>
</div>

<br />
<br />

Views/Parametros/_Consultar.cshtml
@model AppWebHojaCosto.Models.PARAMETROS_PN

@using (Html.BeginForm("Consultar", "Parametros", FormMethod.Post, new { id = "FrmConsulta" }))
{
    @Html.ValidationSummary(true)
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(model => model._TBL_PARAM_PN.PpFactorS, new { @class = "control-label" })
                @Html.DropDownListFor(model => model.Factor, new SelectList(
                  new List<Object>{
                       new { value = "" , text = "Seleccione"  },
                       //new { value = "FR" , text = "Factor Real"  },
                       new { value = "FE" , text = "Factor Estimado" }
                    },
                  "value",
                  "text",
                   0), new { @id = "Tipo", @class = "form-control", @onclick = "FiltroMarca();" })
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m._TBL_PARAM_PN.PpMarcaS, new { @class = "control-label" })
                @*@Html.DropDownListFor(m => m._TBL_PARAM_PN.PpMarcaS, new SelectList(Model.Marcas, "Value", "Text"), new { @id = "Marca", @class = "form-control", @required = "required" })*@
                
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" id="marca" name="marca" required />
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button" id="ver-todo-marcas">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m._TBL_PARAM_PN.PpColeccionS, new { @class = "control-label" })
                @*@Html.DropDownListFor(m => m._TBL_PARAM_PN.PpColeccionS, new SelectList(Model.Colecciones, "Value", "Text"), new { @id = "Coleccion", @class = "form-control", @required = "required" })*@
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" id="coleccion" name="coleccion" required />
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button" id="ver-todo-coleccion">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m._TBL_PARAM_PN.PpLineaS, new { @class = "control-label" })
                @*@Html.DropDownListFor(m => m._TBL_PARAM_PN.PpLineaS, new SelectList(Model.Lineas, "Value", "Text"), new { @id = "Linea", @class = "form-control", @required = "required" })*@
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" id="linea" name="linea" required />
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button" id="ver-todo-linea">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m._TBL_PARAM_PN.PpSubLineaS, new { @class = "control-label" })
                @*@Html.DropDownListFor(m => m._TBL_PARAM_PN.PpSubLineaS, new SelectList(Model.Sublineas, "Value", "Text"), new { @id = "Sublinea", @class = "form-control", @required = "required" })*@
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" id="sublinea" name="sublinea" required />
                    <span class="input-group-append">
                        <button class="btn btn-outline-secondary border-left-0 border" type="button" id="ver-todo-sublinea">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <div class="col-md-2">
                <div style="height:33px; width:10px;"></div>
                <button type="submit" id="btnConsultar" class="btn btn-sm btn-dark"><span class="fa fa-search"></span> Consultar</button>
                <button type="submit" id="btnNuevo" class="btn btn-sm btn-dark"><span class="fa fa-plus-circle"></span> Nuevo</button>
                <button type="button" id="btnLimpiar" class="btn btn-sm btn-dark" onclick="return false;"><span class="fa fa-undo"></span> Limpiar</button>
            </div>
        </div>
    </div>
}